# frozen_string_literal: true

require 'rails_helper'
require_relative '../../app/services/navigation_builder'

describe NavigationBuilder do
  let(:user) { create(:user) }
  let(:request_mock) do
    instance_double(
      'ActionDispatch::Request',
      path: '/records',
      url: 'http://example.com/records',
      path_parameters: { controller: 'records', action: 'index' },
      query_parameters: {}
    )
  end

  let(:builder) { NavigationBuilder.new(user, request_mock) }

  describe '#main_navigation' do
    it 'returns array of navigation items' do
      nav = builder.main_navigation

      expect(nav).to be_an(Array)
      expect(nav).not_to be_empty
    end

    it 'includes Dashboard navigation item' do
      nav = builder.main_navigation
      dashboard = nav.find { |item| item.label == 'Dashboard' }

      expect(dashboard).not_to be_nil
      expect(dashboard.label).to eq('Dashboard')
    end

    it 'includes Records with submenu' do
      nav = builder.main_navigation
      records = nav.find { |item| item.label == 'Records' }

      expect(records).not_to be_nil
      expect(records.children.length).to be > 0
    end

    it 'generates proper Rails routes using framework helpers' do
      nav = builder.main_navigation
      records = nav.find { |item| item.label == 'Records' }

      # Path should be generated by Rails routing helpers
      expect(records.path).to include('/records')
    end

    it 'marks current navigation as active' do
      nav = builder.main_navigation
      records = nav.find { |item| item.label == 'Records' }

      expect(records.active?).to be_truthy
    end
  end

  describe '#user_navigation' do
    it 'returns empty array when no user' do
      builder_no_user = NavigationBuilder.new(nil, request_mock)
      nav = builder_no_user.user_navigation

      expect(nav).to be_empty
    end

    it 'returns user navigation items when authenticated' do
      nav = builder.user_navigation

      expect(nav).not_to be_empty
      expect(nav.first.label).to eq(user.full_name)
    end

    it 'includes user submenu with settings and sign out' do
      nav = builder.user_navigation
      user_item = nav.first

      expect(user_item.children.length).to be > 0
      labels = user_item.children.map(&:label)
      expect(labels).to include('Profile Settings', 'Sign Out')
    end
  end

  describe '#breadcrumbs' do
    it 'returns breadcrumb trail array' do
      breadcrumbs = builder.breadcrumbs

      expect(breadcrumbs).to be_an(Array)
      expect(breadcrumbs).not_to be_empty
    end

    it 'always starts with Home breadcrumb' do
      breadcrumbs = builder.breadcrumbs

      expect(breadcrumbs.first[:label]).to eq('Home')
    end

    it 'marks last breadcrumb as current' do
      breadcrumbs = builder.breadcrumbs

      expect(breadcrumbs.last[:current]).to be_truthy
    end

    it 'generates breadcrumbs for records list page' do
      breadcrumbs = builder.breadcrumbs

      labels = breadcrumbs.map { |crumb| crumb[:label] }
      expect(labels).to include('Home', 'Records')
    end
  end

  describe '#is_active?' do
    it 'determines active route by controller name' do
      expect(builder.is_active?('records')).to be_truthy
    end

    it 'determines active route by controller and action' do
      expect(builder.is_active?('records', 'index')).to be_truthy
      expect(builder.is_active?('records', 'show')).to be_falsy
    end

    it 'returns false for non-matching controller' do
      expect(builder.is_active?('softwares')).to be_falsy
    end
  end

  describe '#is_root?' do
    it 'returns true for root path' do
      root_request = instance_double('ActionDispatch::Request', path: '/')
      root_builder = NavigationBuilder.new(user, root_request)

      expect(root_builder.is_root?).to be_truthy
    end

    it 'returns false for non-root path' do
      expect(builder.is_root?).to be_falsy
    end
  end

  describe '#resource_navigation' do
    it 'generates resource paths using framework helpers' do
      resource_nav = builder.resource_navigation('record')

      expect(resource_nav).to have_key(:index)
      expect(resource_nav).to have_key(:new)
      expect(resource_nav[:index]).to include('/records')
    end

    it 'generates resource detail paths when ID provided' do
      resource_id = 123
      resource_nav = builder.resource_navigation('record', resource_id)

      expect(resource_nav).to have_key(:show)
      expect(resource_nav).to have_key(:edit)
      expect(resource_nav).to have_key(:delete)
      expect(resource_nav[:show]).to include('123')
    end
  end

  describe '#category_navigation' do
    let(:categories) do
      [
        { id: 1, name: 'Mechanical', icon: 'gear', count: 5 },
        { id: 2, name: 'Electrical', icon: 'zap', count: 3 }
      ]
    end

    it 'builds navigation from categories array' do
      nav = builder.category_navigation(categories)

      expect(nav.length).to eq(2)
      expect(nav.first.label).to eq('Mechanical')
    end

    it 'includes category badge count' do
      nav = builder.category_navigation(categories)

      expect(nav.first.badge).to eq(5)
    end

    it 'marks active category' do
      query_request = instance_double(
        'ActionDispatch::Request',
        path: '/records',
        query_parameters: { 'category' => '1' }
      )
      query_builder = NavigationBuilder.new(user, query_request)

      nav = query_builder.category_navigation(categories)

      expect(nav.first.active?).to be_truthy
    end
  end

  describe '#pagination_navigation' do
    it 'generates pagination links using framework helpers' do
      pagination = builder.pagination_navigation(1, 5, 'record')

      expect(pagination[:current_page]).to eq(1)
      expect(pagination[:total_pages]).to eq(5)
      expect(pagination[:has_previous]).to be_falsy
      expect(pagination[:has_next]).to be_truthy
    end

    it 'generates previous link when not on first page' do
      pagination = builder.pagination_navigation(3, 5, 'record')

      expect(pagination[:has_previous]).to be_truthy
      expect(pagination[:previous_link]).to include('page=2')
    end

    it 'generates next link when not on last page' do
      pagination = builder.pagination_navigation(3, 5, 'record')

      expect(pagination[:has_next]).to be_truthy
      expect(pagination[:next_link]).to include('page=4')
    end

    it 'returns no next link when on last page' do
      pagination = builder.pagination_navigation(5, 5, 'record')

      expect(pagination[:has_next]).to be_falsy
    end
  end

  describe '#nested_navigation' do
    let(:nested_items) do
      [
        {
          label: 'Parent 1',
          path: '/parent1',
          children: [
            { label: 'Child 1', path: '/parent1/child1' }
          ]
        }
      ]
    end

    it 'builds nested navigation structure' do
      nav = builder.nested_navigation(nested_items)

      expect(nav.first.label).to eq('Parent 1')
      expect(nav.first.children.length).to eq(1)
      expect(nav.first.children.first.label).to eq('Child 1')
    end

    it 'respects maximum depth parameter' do
      deep_items = {
        label: 'Level 1',
        path: '/',
        children: [
          {
            label: 'Level 2',
            path: '/',
            children: [
              {
                label: 'Level 3',
                path: '/',
                children: [
                  { label: 'Level 4', path: '/' }
                ]
              }
            ]
          }
        ]
      }

      nav = builder.nested_navigation([deep_items], 0, 2)

      # Should only go 2 levels deep
      expect(nav.first.children.first.children).to be_empty
    end
  end

  describe '#mobile_navigation' do
    it 'returns mobile navigation structure' do
      mobile = builder.mobile_navigation

      expect(mobile).to have_key(:primary)
      expect(mobile).to have_key(:secondary)
      expect(mobile).to have_key(:footer_links)
    end

    it 'includes footer links for mobile menu' do
      mobile = builder.mobile_navigation

      footer_labels = mobile[:footer_links].map { |link| link[:label] }
      expect(footer_labels).to include('About', 'Help', 'Settings')
    end
  end

  describe '#authorized_navigation' do
    it 'filters navigation based on user authorization' do
      nav = builder.authorized_navigation(user)

      # Should only include public items or user-authorized items
      expect(nav).not_to be_empty
    end

    it 'returns empty for unauthorized user' do
      nav = builder.authorized_navigation(nil)

      expect(nav).not_to be_empty  # Public items still visible
    end
  end

  describe '#is_authorized?' do
    it 'returns true for public navigation items' do
      expect(builder.is_authorized?(user, 'Dashboard')).to be_truthy
    end

    it 'returns false for restricted items without user' do
      expect(builder.is_authorized?(nil, 'My Records')).to be_falsy
    end

    it 'returns true for user-specific items with authenticated user' do
      expect(builder.is_authorized?(user, 'My Records')).to be_truthy
    end
  end

  describe 'Framework integration' do
    it 'uses Rails routing helpers to generate paths' do
      nav = builder.main_navigation

      nav.each do |item|
        expect(item.path).to start_with('/')
      end
    end

    it 'generates valid Rails URL patterns' do
      nav = builder.main_navigation
      records = nav.find { |item| item.label == 'Records' }

      expect(records.path).to match(/\/records/)
    end

    it 'properly extracts request parameters for navigation state' do
      expect(builder.is_active?('records')).to be_truthy
    end
  end

  describe 'Uniform navigation principles' do
    it 'maintains consistent NavigationItem structure' do
      nav = builder.main_navigation

      nav.each do |item|
        expect(item).to respond_to(:label)
        expect(item).to respond_to(:path)
        expect(item).to respond_to(:icon)
        expect(item).to respond_to(:active?)
        expect(item).to respond_to(:children)
      end
    end

    it 'supports hierarchical navigation consistently' do
      nav = builder.main_navigation

      records_item = nav.find { |item| item.label == 'Records' }
      expect(records_item.children).to all(respond_to(:label, :path, :icon, :active?, :children))
    end

    it 'provides uniform active state determination' do
      nav = builder.main_navigation

      nav.each do |item|
        expect(item.active?).to be(true).or be(false)
      end
    end
  end
end
